name: Azure Deploy Budgeta UI 

on:
  push:
    branches:
      - main

env:
  BUDGETA_SDK_API_HOST: ${{ secrets.BUDGETA_SDK_API_HOST }}
  BUDGETA_SDK_API_PORT: ${{ secrets.BUDGETA_SDK_API_PORT }}
  BUDGETA_SDK_API_PROTOCOL: ${{ secrets.BUDGETA_SDK_API_PROTOCOL }}
  BUDGETA_UI_HOST: ${{secrets.BUDGETA_UI_HOST}}
  BUDGETA_UI_PROTOCOL: ${{secrets.BUDGETA_UI_PROTOCOL}}
  BUDGETA_UI_PORT: ${{secrets.BUDGETA_UI_PORT}}

jobs:
  # print-env-variables:
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: 'production'

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Print Environment Variables
  #     run: |
  #       echo "BUDGETA_SDK_API_HOST: $BUDGETA_SDK_API_HOST"
  #       echo "BUDGETA_SDK_API_PORT: $BUDGETA_SDK_API_PORT"

  build:
    runs-on: ubuntu-latest
    environment:
      name: 'production'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies UI
      run: npm install
      working-directory: ${{ github.workspace }}/ui

    - name: Install Dependencies Express Server
      run: npm install
      working-directory: ${{ github.workspace }}/setup/express_server

    - name: Build React app UI
      run: npm run build
      working-directory: ${{ github.workspace }}/ui

    - name: Copy React build to Express server
      run: cp -R ${{ github.workspace }}/ui/dist ${{ github.workspace }}/setup/express_server/dist

    - name: Archive production artifacts Express Server
      uses: actions/upload-artifact@v2
      with:
        name: express_server
        path: ${{ github.workspace }}/setup/express_server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: express_server
          path: '${{ github.workspace }}/setup/express_server'

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS_UI }}'

      - name: Deploy Express Server to Azure Web Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'budgeta'
          slot-name: 'production'
          package: ${{ github.workspace }}/setup/express_server
