name: Build and deploy Spring app to Azure Web App - budgeta-sdk-api

env:
  BUDGETA_MONGODB_HOST: ${{ secrets.BUDGETA_MONGODB_HOST }}

defaults:
  run:
    working-directory: sdk-api # The working directory path

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: budgeta-api
          path: '${{ github.workspace }}/sdk-api/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: budgeta-api
          path: '${{ github.workspace }}/target'

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
            
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'budgeta-api'
          package: '${{ github.workspace }}/target/*.jar'
